### ISSUE TITLE
You guys don't own the full Minecraft Bedrock Vanilla Resource Pack.

### ISSUE THREAD

**Issue by BestSpark687090** [ZtechNetwork/MCBVanillaResourcePack#2]
Alright, so on every Windows 10 Computer, there's this hidden folder called WindowsApps. It's located in C:\Program Files\WindowsApps. And usually, you can't get in. But I managed to get in by taking ownership of it. And the original texture pack would be located in C:\Program Files\WindowsApps\Microsoft.MinecraftUWP_1.16.20102.0_x64__8wekyb3d8bbwe\data\resource_packs\vanilla. Remember, you have to take ownership of the folder.
Thanks for reading!
-BestSpark687090 
![image](https://user-images.githubusercontent.com/73793381/108606288-e6c9f200-737e-11eb-83d4-5bad534b819c.png)

**Comment by LeronHinds** [comment]
1. We've never claimed that we own the resource pack, behavior pack nor the assets within them which is also stated in our README. This repository was made simply for the people who create custom resource packs and use Github as a platform for their projects.
2. This hidden folder is missing many assets from the recent versions of the game so this isn't an advised way of getting the resource pack.
3. This repository derives from the official download mirrors provided by Mojang and Microsoft for the [public](https://aka.ms/resourcepacktemplate) and [beta](https://aka.ms/MinecraftBetaResources) releases of the game.

**Comment by BestSpark687090** [comment]
Oh, sorry!
