### ISSUE TITLE
locating

### ISSUE THREAD

**Issue by Nuerfr** [ZtechNetwork/MCBVanillaResourcePack#3]
where is the file of lightning strike?

**Comment by CoolLoong** [comment]
Please update

**Comment by RedStoneCraftGG** [comment]
At behavior packs

**Comment by LeronHinds** [comment]
Yes, the lightning bolt entity can only be controlled in [behavior packs](https://github.com/ZtechNetwork/MCBVanillaBehaviorPack/blob/master/entities/lightning_bolt.json) as far as I know.
