### ISSUE TITLE
New door, trapdoor sounds

### ISSUE THREAD

**Issue by BeetrootGuy** [ZtechNetwork/MCBVanillaResourcePack#6]
Hello, so in 1.19.60 update they added new sounds for doors and trapdoors, but there aren't any in this pack

**Comment by JtheK1984** [comment]
I have the same Problem, my Doorsound will not work anymore

**Comment by KurojakiKaoru** [comment]
The pack has been updated for the latest version (1.19.63), it should now contain those sounds.

**Comment by JtheK1984** [comment]
Thx. Your make a great Job and i love your Resource Pack
